[project]
name = "tc-ml-books"
version = "0.1.0"
description = "Projeto para recomendaÃ§Ãµes de livros."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi~=0.116.0",
    "uvicorn[standard]~=0.35.0",
]
